In [ ]:
import pandas as pd
from global_land_mask import globe

dff = pd.read_csv("grouped1no0j.csv")
dff = dff.drop(dff.columns[[0]],axis = 1)
dff = dff.drop(dff[dff.Longitude > 180].index)
dff = dff.drop(dff[globe.is_land(dff.Latitude, dff.Longitude)].index)

dff

In [120]:
import pandas as pd

middleEast = dff.copy()
middleEast = middleEast[(middleEast['Latitude'] < 50) & (middleEast['Latitude'] > 29)] 
middleEast = middleEast[(middleEast['Longitude'] > -5) & (middleEast['Longitude'] < 36)]
middleEast = middleEast.drop(middleEast[((middleEast['Latitude'] > 40.625) & (middleEast['Longitude'] > 26.625))].index)
middleEast = middleEast.drop(middleEast[((middleEast['Latitude'] > 43) & (middleEast['Longitude'] < 2))].index)
middleEast = middleEast.drop(middleEast[(middleEast['power_max'] > 85000000)].index) #outlier
middleEast['latlong'] = middleEast['Latitude'].astype("string")+','+middleEast['Longitude'].astype("string")
middleEast["power_mean"] = middleEast["power_mean"].astype(int)
middleEast["power_max"] = middleEast["power_max"].astype(int)
middleEast

,Latitude,Longitude,Month,power_mean,power_min,power_max,lightning_count,latlong
544,35.0,12.0,2009-12,5467,1970.32,9476,5,"35.0,12.0"
1311,38.0,4.0,2009-12,3589,25.38,71901,506,"38.0,4.0"
1315,38.0,3.0,2009-12,11949,52.57,468368,128,"38.0,3.0"
1320,38.0,2.0,2009-12,5350,41.18,93698,87,"38.0,2.0"
1331,38.0,26.0,2009-12,5040,27.78,513133,2448,"38.0,26.0"
...,...,...,...,...,...,...,...,...
835506,44.0,9.0,2020-02,232,5.57,1631,16,"44.0,9.0"
835623,44.0,15.0,2020-02,1970,10.33,40299,87,"44.0,15.0"
835636,44.0,10.0,2020-02,850,4.33,32550,107,"44.0,10.0"
835642,44.0,13.0,2020-02,7557,6.18,218133,175,"44.0,13.0"
835645,44.0,14.0,2020-02,5128,9.97,147276,98,"44.0,14.0"

In [121]:
#mediterranean intensity map
# https://plotly.com/python-api-reference/generated/plotly.express.scatter_geo.html

import plotly.express as px
df = middleEast.copy()
fig = px.scatter_geo(df, lat='Latitude', lon='Longitude', color="power_max",
                     hover_name="latlong", size="power_mean",
                     animation_frame="Month",
                     projection="winkel tripel",
                     hover_data={"lightning_count":True, "power_max":True,'power_mean':True,'Latitude':False,'Longitude':False,'Month':False},
                     center=dict(lat=38, lon=14), 
                     width=1400,
                     height=800,
                     size_max=25,
                     range_color=[0,df["power_max"].max()],
                     title="Lightning intensity over the mediterranean per 0.5 degrees squared | Dec.,Jan.,Feb. 2009-2020",
                     labels={'lightning_count':'Lightning Count','power_max':'Strongest Lightning (J)','power_mean':'Average Lightning Power (J)'})
fig.write_html("Mediterranean Intensity.html")

In [ ]:
import pandas as pd

globalMap = dff.copy()
globalMap['latlong'] = globalMap['Latitude'].astype("string")+','+globalMap['Longitude'].astype("string")
globalMap = globalMap[(globalMap['lightning_count'] > 1)] 
globalMap = globalMap[(globalMap['Latitude'] < 50)] 
globalMap

In [ ]:
#global intensity map

import plotly.express as px
df = globalMap.copy()
fig = px.scatter_geo(df, lat='Latitude', lon='Longitude', color="power_max",
                     hover_name="latlong", size="power_mean",
                     animation_frame="Month",
                     projection="winkel tripel",
                     hover_data={"lightning_count":True, "power_max":True,'power_mean':True,'Latitude':False,'Longitude':False,'Month':False},
                     center=dict(lat=38, lon=14), 
                     width=1400,
                     height=800,
                     size_max=25,
                     range_color=[0,df["power_max"].max()],
                     title="Lightning intensity over water worldwide per 1 degree squared | Dec.,Jan.,Feb. 2009-2020",
                     labels={'lightning_count':'Lightning Count','power_max':'Strongest Lightning (J)','power_mean':'Average Lightning Power (J)'})
fig.write_html("Worldwide Intensity over water.html")